version: '3.8'
services:
  db:
    image: docker.io/postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${EXPOSED_PG_PORT}:5432"
    networks:
      - odoo-network

  odoo:
    image: docker.io/odoo:${ODOO_VERSION}
    container_name: odoo-app
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_ADMIN_PASSWORD=${ODOO_MASTER_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "${EXPOSED_ODOO_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf.template:/etc/odoo/odoo.conf.template
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    command: ["odoo"]
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge
