version: "3.8"
services:
  db:
    image: docker.io/postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${EXPOSED_PG_PORT}:5432"
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    image: docker.io/odoo:${ODOO_VERSION}
    container_name: odoo-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_ADMIN_PASSWORD=${ODOO_MASTER_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      # Force TCP connection instead of Unix socket
      - PGHOST=db
      - PGPORT=5432
    ports:
      - "${EXPOSED_ODOO_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    command: >
      sh -c "sleep 5  # Wait for PostgreSQL to be fully ready
      && odoo"
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge
